name: Build app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app
    - name: Build app
      run: python setup.py py2app
    - name: Upload app
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: dist/Hello World.app